user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

jwt_user:
    type: rest
    prefix: /api
    resource: "@UserBundle/Resources/config/routes.yml"

hello_world:
    type: rest
    prefix: /api/v1
    resource: "@AppBundle/Controller/HelloController.php"

