security:
    erase_credentials: false
    encoders:
            UserBundle\Entity\Users: plaintext
            Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
            ROLE_ADMIN: ROLE_USER

    access_control:
            - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
#
    providers:
            in_memory:
                            memory:
                                users:
                                    user:  { password: user, roles: [ 'ROLE_USER' ] }
                                    #admin: { password: password, roles: [ 'ROLE_ADMIN' ] }
            fos_userbundle:
              id: fos_user.user_provider.username

    firewalls:
        login:
                pattern:  ^/api/v1/login
                stateless: true
                anonymous: false
                provider:   fos_userbundle
                form_login:
                    check_path:               /api/v1/logins/checks
                    username_parameter:       username
                    password_parameter:       password
                    success_handler:          lexik_jwt_authentication.handler.authentication_success
                    failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                    require_previous_session: false
                logout:
                    path: /api/v1/logout
        api:
                pattern:   ^/api/v1
                stateless: true
                lexik_jwt: ~

#        dev:
#                    pattern: ^/(_(profiler|wdt|error)|css|images|js)/
#                    security: false
        default:
                    anonymous: ~